#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_WIZFIRST                            101
#define IDD_WIZSETDOWNLOAD                      103
#define IDD_ZIPDLG                              105
#define IDD_WIZINSTALL                          110
#define IDD_TLSET                               114
#define IDD_TLADVSET                            116
#define IDD_WIZDOWNLOAD                         119
#define IDD_WIZAPPSSET                          122
#define IDD_INITINSTALLER                       125
#define IDD_DLGLIST                             128
#define IDC_DETAIL                              1000
#define IDC_FIRSTMSG                            1000
#define IDC_LIST                                1001
#define IDC_PROGRESS                            1001
#define IDC_PROXY                               1001
#define IDC_TEX2IMG                             1001
#define IDC_DIR                                 1002
#define IDC_NKF                                 1002
#define IDC_IMAGEMAGICK                         1003
#define IDC_FILE                                1004
#define IDC_PROXYPORT                           1004
#define IDC_MSG                                 1005
#define IDC_ABNRSET                             1008
#define IDC_SETPATH                             1009
#define IDC_CHKTL                               1011
#define IDC_TLURLLIST                           1014
#define IDC_REPOSITORY                          1026
#define IDC_SANSYO_INSTALL                      1028
#define IDC_PAPERA4                             1029
#define IDC_PAPERLETTER                         1031
#define IDC_BTNTLADVSET                         1033
#define IDC_SANSYO                              1036
#define IDC_CHKABNRSET                          1038
#define IDC_CHKDIRINDEP                         1039
#define IDC_SCHEMES                             1040
#define IDC_SANSYO_TEXMFLOCAL                   1042
#define IDC_TEXMFLOCAL                          1043
#define IDC_TEXMFSYSVAR                         1044
#define IDC_SANSYO_TEXMFSYSVAR                  1046
#define IDC_TEXMFSYSCONFIG                      1048
#define IDC_SANSYO_TEXMFSYSCONFIG               1049
#define IDC_TEXMFHOME                           1050
#define IDC_SANSYO_TEXMFHOME                    1052
#define IDC_WRITE18                             1053
#define IDC_FORMATFILE                          1054
#define IDC_DOCTREE                             1055
#define IDC_SOURCETREE                          1056
#define IDC_TEXWORKS                            1057
#define IDC_PATH                                1058
#define IDC_FILEASSOC                           1060
#define IDC_DIRISSET                            1061
#define IDC_INSTALLDIR                          1061
#define IDC_INSTDIR                             1062
#define IDC_TEXDIR                              1062
#define IDC_TL                                  1063
